# $Id: makefile.1 158 2001-03-07 19:49:01Z skaus $
#

all :

clobber : clean
	$(RM) $(RMFLAGS) *.exe *.com *.icd default.mk

clean :
	$(RM) $(RMFLAGS) *.lst *.map *.bin *.bak *.las *.obj $(CFG) *.dmp

